---
title: "Experience"
toc: false
css: ./assets/style.css
---

<section id="teaching-assistant" class="level3">
<div style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;">
<div><h3 class="anchored" data-anchor-id="teaching-assistant">Teaching Assistant</h3>
<p style = "margin-bottom: 0 !important"><strong>Indian Institute of Technology, Gandhinagar</strong>
</p></div>
<div><p><em>Aug'2023-Present</em></p></div>
</div>
<div>
<ul>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span><strong>- Computing Lab</strong>: Conducting lab tasks and grading assignments for multiple semesters.</span><span><em>Aug'2023-Nov'2023; Aug'2024-Present</em></span></li>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span><strong>- Software Engineering &amp; Testing</strong>: Assisted with course delivery and student support.</span><span><em>Jan'2024-May '2024</em></span></li>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span><strong>- Aarohan</strong>: Managed the orientation of 50+ students with a team of 12 TAs.</span><span><em>Dec'2023</em></span></li>
</ul>
</div>
</section>
<section id="it-software-engineer" class="level3">
<div style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;">
<div><h3 class="anchored" data-anchor-id="it-software-engineer">IT Software Engineer</h3>
<p style = "margin-bottom: 0 !important"><strong>Behind Earth Pvt. Ltd, Chennai, Tamil Nadu</strong>
</p></div>
<div><p><em>Feb'2022-Apr-2022</em></p></div>
</div>
<div>
<ul>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Developed and maintained the <a href = "https://maxicabrbs.sg/">Maxi Cab Booking </a> and built the LeadWide websites. </span><span><em></em></span></li>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Enhanced user experience and functionality using WordPress.</span><span><em></em></span></li>
</ul>
</div>
</section>

<section id="website-development" class="level3">
<div style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;">
<div><h3 class="anchored" data-anchor-id="website-development">Website Development</h3>
<p style = "margin-bottom: 0 !important"><strong>DVG Soft Pvt. Ltd, Jaipur, Rajasthan</strong>
</p></div>
<div><p><em>Feb'2021-Feb'2022</em></p></div>
</div>
<div>
<ul>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Developed and designed a website for <a href="https://procemeteryservices.com/">Professional Cemetery Services</a>.</span><span><em></em></span></li>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Created a dashboard page for admin and user management.</span><span><em></em></span></li>
</ul>
</div>
</section>

<section id="software-developer" class="level3">
<div style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;">
<div><h3 class="anchored" data-anchor-id="software-developer">Software Developer</h3>
<p style = "margin-bottom: 0 !important"><strong>Mangal Essakki Innovations Pvt. Ltd, Mumbai,Maharashtra</strong>
</p></div>
<div><p><em>May'2019-Nov'2019</em></p></div>
</div>
<div>
<ul>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Developed MOM’s Kitchen, a food ordering and delivery web app using ReactJS and Firebase.</span><span><em></em></span></li>
<li style = "display: flex; justify-content: space-between; margin-bottom:0 !important; align-items: baseline;"><span>- Designed a website for <a href = "https://ca-gk.com/">CA Ganesh & Kunal</a> to transition the firm’s operations online, focusing on front-end development.</span><span><em></em></span></li>
</ul>
</div>
</section>